plugins {
    kotlin("jvm")
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.shadow)
}

dependencies {
    implementation(libs.clikt)
    implementation(libs.kotlinx.serialization.json)
}

// ─── Generate CliVersion.kt from gradle.properties ─────────
val generateVersion by tasks.registering {
    val versionName = project.property("VERSION_NAME") as String
    val groupId = project.property("GROUP") as String
    val outputDir = layout.buildDirectory.dir("generated/version/kotlin")

    inputs.property("versionName", versionName)
    outputs.dir(outputDir)

    doLast {
        val dir = outputDir.get().asFile.resolve(
            "com/ae/design/cli",
        )
        dir.mkdirs()
        dir.resolve("CliVersion.kt").writeText(
            """
            |// Generated by Gradle — do not edit.
            |package com.ae.design.cli
            |
            |object CliVersion {
            |    const val NAME = "$versionName"
            |    const val FOUNDATION = "$groupId:foundation:$versionName"
            |    const val COMPONENTS = "$groupId:components:$versionName"
            |}
            """.trimMargin(),
        )
    }
}

kotlin.sourceSets.main {
    kotlin.srcDir(generateVersion.map { it.outputs.files.singleFile })
}

tasks.shadowJar {
    archiveBaseName.set("aedesign")
    archiveClassifier.set("")
    archiveVersion.set("")
    manifest {
        attributes("Main-Class" to "com.ae.design.cli.MainKt")
    }
}
